Fantom-foundation/Carmen

- README.md
- go/carmen/example_test.go
This PR adds a `README` file to projects root.
> Project readme

- go/state/flush_benchmark_test.go
- go/state/gostate/go_state.go
This should improve the flush performance on high-latency disks - flushing archive and live state in parallel.
> Flush live and archive state in parallel

- README.md
This PR adds a new section into the readme, which contains performance numbers.
The numbers are from the blog, which is also linked from the Readme
> extends  readme with performance results

- scripts/license/add_license_header.sh
This PR adds option to exclude directories or files by blacklisting them in script's array.
> Add option to exclude directories for license script

- Jenkinsfile
- go/backend/ldb.go
- scripts/license/add_license_header.sh
This PR adds check into jenkins pipeline, that all files have correct license header.
> Add license headers CI check

- go/database/mpt/forest_test.go
- go/database/mpt/nodes.go
- go/database/mpt/nodes_test.go
This PR add support for getting nodes from the storage root down to a storage.
It is implemented as an utility function that uses the `NodeSource` to fetch nodes and passes them to the `NodeVisitor`.
This feature is preparation for the witness proof where the nodes on a path will need to be obtained.
> implements node iterator for a storage

- go/carmen/amount.go
- go/carmen/amount_test.go
This PR extends `Amount` type by uint256 getter.
> Add uint256 getter for Amount

- go/common/tribool/tribool.go
- go/common/tribool/tribool_test.go
this PR introduces a new type `Tribool`
It is a kind of boolean type, which can be apart from `true/false` also unknown.
> introduces tribool type

- go/database/mpt/nodes_test.go
this PR extends the node testing framework with the storage hash computation.
> sets storage hash in node testing framework

- go/database/mpt/nibble.go
- go/database/mpt/nibble_test.go
- go/database/mpt/path.go
- go/database/mpt/path_test.go
- go/database/mpt/proof.go
- go/database/mpt/proof_test.go
This PR implements proof manipulation utils, in particular it offers:
* Extraction of a proof from another proof based on address and key(s)
* Merge of proofs
> implements extraction and merge of witness proof

- go/database/mpt/proof.go
- go/database/mpt/proof_test.go
This PR implements proving of account addresses and keys agains the given witness proof.
> proof addresses and keys

- go/carmen/carmen.go
- go/carmen/carmen_mock.go
- go/carmen/transaction.go
- go/carmen/transaction_test.go
- go/state/state_db.go
- go/state/state_db_mock.go
- go/state/state_db_test.go
This PR solves this issue https://github.com/Fantom-foundation/Carmen/issues/919
> Add support for EIP-6780

- go/database/mpt/write_buffer.go
This PR fixes a synchronization issue in the write buffer discovered by issue #953.
Before this change, the following sequence of events would have been possible (A and B are different goroutines):
- (A) a node in the write buffer is selected for being flushed
- (B) the node is restored, write protection is acquired, the node modified, and write protection abandoned
- (A) write protection on the node is acquired and the node gets flushed
In the last step, the node may be in a state where hashes are invalid. In such a situation, the node can not be flushed.
This change prevents the node from being restored between its selection for being flushed and the acquisition of write permissions.
> Avoid nodes to be recovered from write buffer before being written

- go/database/mpt/forest.go
- go/database/mpt/forest_test.go
This PR fixes a bug in the forest which can lead to the accidental creation of multiple node instances associated with the same ID. 
For a detailed discussion of the addressed issue see #948.
> Recover nodes from write buffer

- go/database/mpt/tool/stress.go
This PR resolves type mishmash between macOs and Linux, and fixes build on macOs
> fixes Statfs_t syscalls for macOs

- go/database/mpt/proof_test.go
This PR extends test coverage of the witness proof implementation. It covers 100% except two methods that are not implemented. 
The coverage was probably somehow reduced by the last review iterations when this feature was implemented and it was missed. This PR fixes this issue.
> extends test coverage of witness proof

- go/database/mpt/archive_trie.go
- go/database/mpt/archive_trie_test.go
This PR adds checkpoint and recovery support to root lists. This is step 3 towards supporting Archive checkpoints and quick recovery in Carmen.
This is part of #946.
> Add checkpoint support to root lists

- go/database/mpt/io/archive.go
- go/database/mpt/io/archive_test.go
- go/database/mpt/io/live.go
- go/database/mpt/io/live_test.go
This PR specifies errors when running incorrect command+genesis combination.
> Specify import errors.

- go/common/heap/heap.go
- go/common/heap/heap_test.go
> Add generic heap container

- go/backend/stock/file/file_test.go
- go/backend/stock/file/readonly.go
- go/backend/stock/file/readonly_test.go
- go/backend/stock/stock.go
This PR introduces a read-only stock
> Introduces a read-only stock

- go/database/mpt/io/live.go
- go/database/mpt/io/parallel_visit.go
- go/database/mpt/io/parallel_visit_test.go
> Fix support for visitor without response

- go/database/mpt/archive_trie.go
- go/database/mpt/archive_trie_test.go
This PR fixes two issues with the checkpoint/recovery implementation for root lists:
- before this PR roots have not been flushed during the checkpoint preparation step
- before this PR, the recovery of a pending commit root list did not promote the pending commit to the committed value
Both these issues are fixed by this PR and corresponding unit tests are added.
This is part of #1010.
> Fix checkpoint and recovery of root lists

- go/backend/stock/file/file.go
- go/backend/stock/file/file_test.go
This PR fixes an issue in the stock recovery. Before this change, when recovering to a pending checkpoint, the data was recovered but the pending checkpoint was not promoted to the committed checkpoint. This PR fixes this.
Fixes #1017
> Fix recovery of file stock checkpoints

- go/database/mpt/archive_trie.go
- go/database/mpt/archive_trie_test.go
- go/database/mpt/live_trie.go
This fix adds support for recovering a meta data file in the archive that is required to be in proper JSON format at any time. During recovery, a clean version of this file is re-created.
Fixes #1018
> Add restoration of forest meta data when recovering archive

- go/database/mpt/root_hash_test.go
- go/database/mpt/state_test.go
This PR updates tests of State to properly release resources to reduce memory consumption of the tests.
> releases properly resources for State tests

- go/database/mpt/archive_trie_test.go
This PR fixes #994 by disabling node flusher for the ArchiveTrie used in the test. 
It was discovered that the node flusher created (flushed from the cache) some extra node after the trie was already considered corrupted.  It caused the test to fail. 
Since such a situation cannot  happen in real scenario, because a corrupted ArchiveTrie is already stopped, this issue was a test configuration.
> Disable node flusher in recovery test by setting a high frequency

- Jenkinsfile
This PR removes explicit go path configuration as it is no more needed
> removes extra go path configuration

- go/carmen/database_test.go
This PR updates tests of Carmen facade to exercise the new method `GetAccountElements`. This method was covered only in the `example_test.go` file
> updates witness proof test in facade to exercise account
