Fantom-foundation/Carmen

go/carmen/block_test.go, go/carmen/carmen_test.go, go/carmen/configurations_test.go, go/carmen/database.go, go/carmen/database_test.go, go/carmen/property.go, go/carmen/transaction_test.go, go/state/state_db.go
this PR removes memory leak in tests caused by failing `Close()` of database in tests. 
furthermore it reduces size of caches. 
It fixes #833
=> fix memory leak in tests

go/database/mpt/state.go, go/database/mpt/state_test.go
Everytime when MptState is being Flushed, the codes file is written to the disk, even when no code have been modified.
This affects event the time of Carmen closing, as the flush is called here several times:
This PR adds a codeDirty flag, which avoids these unnecessary overrides.
This also adds proper codeMutex locking into the Flush and GetMemoryFootprint.
We may want to use ReadWrite lock in the future, however until now, we just supposed there is no concurrency of Flush/GetMemoryFootprint with code writes.
=> Fix multiple flushing of codes

go/database/mpt/forest.go, go/database/mpt/forest_test.go
this PR marks nodes clean when they are flushed. This causes that repeated call to` Flush()` does not store nodes again and again. 
This change should boost performance as unnecessary I/O is avoided.
=> Mark nodes clean when they are flushed

go/database/mpt/archive_trie_test.go
This PR verifies that huge slices of hash roots are growing sub linearly.  
It is to avoid situation where this slice consumes already GiBs of memory as a consequence of storing minions of roots, and suddenly doubles memory consumption caused by expanded capacity of this slice. 
It basically tests only how current golang behaves, but should serve as a validation that further versions or configurations do not change.
=> tests how standard slice grows

go/database/mpt/state_test.go
This benchmark is designed to measure the costs for flush operations.
To run the benchmark use the following command:
```
go test ./database/mpt -run none -bench BenchmarkMptState_ArchiveFlush --benchtime 10s
```
This command will produce benchmark results like this:
```
goos: linux
goarch: amd64
pkg: github.com/Fantom-foundation/Carmen/go/database/mpt
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
BenchmarkMptState_ArchiveFlush-12               	      56	 178799258 ns/op
BenchmarkMptState_ArchiveFlushForcedDirty-12    	      48	 224348680 ns/op
PASS
ok  	github.com/Fantom-foundation/Carmen/go/database/mpt	41.867s
```
=> Add benchmark for flushing MPT States

go/carmen/database.go, go/carmen/database_test.go, go/state/gostate/archive_state.go, go/state/gostate/go_state.go
this PR removes check for the `lastBlock` from the archive query of the Carmen facade.
this check used to cause error: https://github.com/Fantom-foundation/Carmen/issues/845
the problem was that while the head state block is being committed, the block may be already available in the archive, before the `lastBlock` counter is incremented.  It was fixed the way that this check is removed as it  serves rather for sequencing new head state blocks. 
Another approach would be to capture this counter in the same lock as the one managing the head state, though it would unnecessarily block running parallel archive queries. I.e. such an approach was not taken.
=> removes check of last block from history queries

scripts/license/add_license_header.sh
This PR adjusts the license generator script, that appended whitespace on empty lines. This caused `clang-format` tool to fail, so the jenkins pipeline always failed.
=> Fix license header script empty line

go/state/state_db.go, go/state/state_db_mock.go, go/state/state_db_test.go
This PR adds `TransientStorage` to `stateDB` with `Get/SetTransientStorage` to the `VMStateDB` interface.
Fixes #858
=> Add transient storage

go/carmen/carmen.go, go/carmen/transaction.go, go/carmen/transaction_test.go
This PR exposes both `SetTransientStorage` and `GetTransientStorage` through the API inside `go/carmen`
=> Add Transient Storage to public API.

go/database/mpt/hasher.go, go/database/mpt/hasher_test.go
this PR makes RLP encoder functions standalone, not part of the `ethHaser`.  These methods did not use any functionality from the hasher while creating the instance is complicated, it needs to go through MPT configuration.
=> changes RLP encode methods to standalone, not part of the etHasher

go/database/mpt/decoder.go, go/database/mpt/decoder_test.go
This PR implements a decoder from an RLP encoded byte slice into a Node. 
It uses the intermediate rlp.Item format to convert from the byte slice and then it converts this format to a node.
=> implements rlp node decoder

scripts/license/add_license_header.sh
This change prevents bash to expand wildcard paths. If the script was run from a directory that contains any of wildcard paths defined in `ignore_files` (`ignore_files=('cpp/third_party/*')`), it led to expansion of those paths and calling the `find` method with wrong argument. In this particular case it expanded as follows:
```
! -path cpp/third_party/crc32c cpp/third_party/ethash cpp/third_party/gperftools cpp/third_party/leveldb cpp/third_party/snappy
```
The correct way of passing `! path` argument to `find` method is
```
! -path <path_1> ! -path <path_2> ...
```
The arguments are passed into `find` function via arguments list, which prematurely prevents the expansion of wildcard paths.
=> Prevent license script paths expansion

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go, go/database/mpt/io/archive_test.go, go/database/mpt/io/live_test.go, go/database/mpt/live_trie.go, go/database/mpt/live_trie_test.go, go/database/mpt/tool/verify.go, go/database/mpt/verification.go, go/database/mpt/verification_test.go
This PR adds contract codes verification.
1. Verifies that byte code and inside `codes.dat` match
2. Verifies that any `CodeHash` within a `Forest` is contained within `codes.dat`
3. Warns if there are any codes inside `codes.dat` that are not present within a `Forest`
Fixes #736
=> Codes verification

go/database/mpt/io/live.go, go/database/mpt/io/live_test.go
This PR adds a filter to only include referenced codes in LiveDB genesis data exports. This is a source of non-determinism for the exported data that can result in different genesis file content for equal states.
The PR also extends the test coverage by adding test cases with multiple different codes and code reuse in the state. The export data of those states is checked for being deterministic over several executions.
This fixes #891.
=> Avoid including unused codes in LiveDB export

go/database/mpt/nodes.go, go/database/mpt/proof.go
This PR proposes an API for witness proof.
It includes features for 
* merging and splitting proofs, 
* extraction of proofs from databse
* proving of account and addresses
This PR creates only stub methods and API, implementation will follow-up
=> proposes API for witness proofs

go/database/mpt/decoder.go, go/database/mpt/decoder_test.go, go/database/mpt/hasher.go, go/database/mpt/hasher_test.go, go/database/mpt/nodes_test.go, go/database/mpt/rlp/rlp.go
This PR fixes RLP decoder of embedded nodes. 
* It extends the testing framework to track embedded nodes
* It fixes decoding of embedded nodes, in particular they are encoded as an` rlp.List` which contains a value node, not an `rlp.String`, which was previously wrongly assumed. 
* furthermore decoding of common.Value was fixed in cases when prefix bytes contain zeros, the decoded value used to be wrongly aligned 
* tests were fixed to follow new changes
* new end-to-end tests were added, which tests the embedded nodes and values that are < 32bytes
* previous method that decodes embedded nodes was removed as embedded nodes are stored in standard rlp code and can be decoded by calling the common decoding method
=> fix embedded nodes rlp decoder

go/database/mpt/forest_test.go, go/database/mpt/nodes.go, go/database/mpt/nodes_test.go
This PR updates methods to visit path in the MPT in the way that terminal nodes are visited even when their path in the MPT was not matched. In this case such nodes are terminal and are last returned. 
Exception are Empty node and a Branch node when the path was exhausted - these nodes are not returned.
=> propagates all terminal node except empty one via path iterators

go/database/mpt/proof.go, go/database/mpt/proof_test.go
This PR implements IsValid function for the witness proof.  The proof is invalid if
* hash does not match hashed RLP representation
* if RLP cannot be decoded to a node
=> implements is-valid for witness proof

go/database/mpt/decoder.go, go/database/mpt/decoder_test.go
This PR fixes decoding of RLP nodes back into nodes. 
Since RLP encoded empty children of a branch node are empty strings, the current version used to decode them as a hash with all bytes zero. 
This PR corrects it to store `EmptyNodeEthereumHash` as an empty nodes.
=> decodes RLP children of empty nodes into hash

go/database/mpt/proof.go, go/database/mpt/proof_test.go
This PR fixes propagation of embedded flag.
It was originally assumed that the embedded node is always on the right path.  
Perhaps there may be situations where this is not true - at least a test can be synthesised for this. 
this PR fixes this + extend tests
=> fixes propagation of embedded flag when iterating witness proof

go/database/mpt/decoder.go, go/database/mpt/decoder_test.go, go/database/mpt/proof.go, go/database/mpt/proof_test.go
This PR introduces a new variant of node `DecodedAccountNode`. This is used for an `AccountNode` when decoding from RLP.  The hashed address - the path - may be up to 32bytes and for this reason it does not fit into 20bytes addresses. 
This new type wraps the AccountNode and adds a path to store the RLP decoded Path.  This is furthermore used in `WitnessProof` utilities. 
It fixes #900
=> introduces decoded account node to store potentially long paths

go/common/tribool/tribool.go, go/common/tribool/tribool_test.go, go/database/mpt/nodes.go, go/database/mpt/nodes_mocks.go, go/database/mpt/nodes_test.go, go/database/mpt/visitor.go
This PR enables tracking of embedded node in the node visitor. The flag is filled in the `visitPathTo` method.
This feature will be used in witness proof not to include embedded nodes as entries in the proof database.
=> allows for tracking embedded node in the node vistior

go/database/mpt/tool/benchmark.go
This PR adds support for collecting [traces](https://pkg.go.dev/runtime/trace) to the MPT benchmark tool.
Tracing support can help identifying synchronization and IO issues in MPT operations.
This PR also fixes a bug: CPU profiling could not be disabled before this change.
=> Add tracing support to MPT benchmark tool

go/database/mpt/proof.go, go/database/mpt/proof_test.go
This PR implements extraction of Witness proof from database.  It contains API + implementation that allows for generating the witness proof for an address and a list of storage keys. 
It iterates the MPT from its root down the account according to the input address. Until the path exists, it keeps storing encountered nodes in the witness proof. The nodes are stored in the witness proof in pairs of their RLP encoding and hash of the encoding. 
If the input contains in addition a list of keys, the storage root of the respective account is iterated for each key from the account down to the storage Value. The nodes are returned RLP and hash encoded the same way. 
The witness proof is returned all the time even if the key or address could not be found. In this case the proof contains only …
=> implements extraction of witness proofs

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go
This PR updates the export of roots to be incremental.
Before this change, every time an Archive was flushed or closed, the full list of roots has been dumped to the root file on the disk. In particular for large archives, covering 85 million blocks, this corresponds to writing more than 3 GiB of data to the disk.
With this change, the Archie is tracking how much roots are already stored on the disk and only writes incremental updates to the disk. As a side-effect, in consecutive `Flush` and `Close` calls, new roots are only written once.
For a benchmark stress-testing the storing of 1M root nodes in an archive, this results in a more than 90% reduction in the time required to flush an archive:
```
pkg: github.com/Fantom-foundation/Carmen/go/database/mpt
cpu: Intel(R) Core(TM) i7-6600U …
```
=> Update storing of archive roots to be incremental

go/database/mpt/forest.go
This mitigates the problem outlined in #948 until its cause has been identified and fixed.
By disabling this feature, the hope is to pass nightly builds and to allow pending PRs to be processed.
=> Disable node flusher to fix nightly builds

go/database/mpt/forest_test.go, go/database/mpt/hasher.go, go/database/mpt/proof.go, go/database/mpt/proof_test.go
This PR extends the method `CreateWitnessProof`, which iterates nodes from a root to a leaf node for a path.
This change fills children hashes (extension node, children of branch node, storage of account) back to the parents for archive node.
These hashes are missing when nodes are loaded from the archive, It caused wrong hashes computed from RLP of those nodes. It then produced a wrong witness proof.
=> Fill missing hashes for archive nodes when visiting path

go/backend/archive/archive_test.go, go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_fuzzing_test.go, go/database/mpt/archive_trie_test.go, go/database/mpt/forest.go, go/database/mpt/forest_test.go, go/database/mpt/io/archive.go, go/database/mpt/io/archive_test.go, go/database/mpt/io/interrupt_test.go, go/database/mpt/io/live.go, go/database/mpt/io/live_test.go, go/database/mpt/live_trie.go, go/database/mpt/live_trie_fuzzing_test.go, go/database/mpt/live_trie_test.go, go/database/mpt/root_hash_test.go, go/database/mpt/state.go, go/database/mpt/state_test.go, go/database/mpt/tool/block.go, go/database/mpt/tool/check.go, go/database/mpt/tool/info.go, go/database/mpt/verification_test.go, go/database/mpt/visitor_test.go, go/state/gostate/configurations.go, go/state/gostate/go_schema4.go, go/state/gostate/go_schema5.go
This PR adds add support for configuring the flush period of the background flusher when creating an MPT State instance.
This is required in order to implement a stress test utility running the database at a higher flush rate than its default rate.
This PR contributes to the investigation of issue #948
**Note for reviewers:**
The main change of this PR is that the former stand-alone `cacheCapacity` parameter is wrapped into a `NodeCacheConfig` struct, extended by the `backgroundFlushPeriod` parameter and requested as a configuration struct in the factory interface. All other changes in the PR are mere adaptations to this interface signature change.
=> Make flush interval configurable

go/Jenkinsfile, go/database/mpt/tool/main.go, go/database/mpt/tool/stress.go
This PR introduces a new sub-command to the MPT tool running capable of performing stress-tests on Carmen's MPT implementation.
This stress test tool allows to reproduce issue #948 when re-enabling the background flusher by undoing #949.
=> Add stress-test sub-command to MPT tool

go/backend/archive/archive.go, go/backend/archive/archive_mock.go, go/backend/archive/archive_test.go, go/backend/archive/ldb/archive.go, go/backend/archive/sqlite/archive.go, go/carmen/block.go, go/carmen/carmen.go, go/carmen/database.go, go/carmen/database_test.go, go/carmen/example_test.go, go/carmen/proof.go, go/carmen/proof_test.go, go/common/witness/proof.go, go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go, go/database/mpt/proof.go, go/database/mpt/proof_test.go, go/state/cppstate/cpp_state.go, go/state/gostate/archive_state.go, go/state/gostate/archive_state_test.go, go/state/gostate/go_state.go, go/state/state.go, go/state/state_mock.go, go/state/synced_state.go
This PR extends the public API of the  `WitnessProof` support. 
* This defines a new package `witness` with a simple `Proof` interface. 
* This interface is implemented by `mpt.WitnessProof`, i.e. the MPT support of the witness proof. 
* The `carmen.HistoricBlockContext` is extended of a new  features to extract the proof, i.e. a new method `GetProof`
* `State` exposes a method  `CreateWitnessProof` called from `carmen.HistoricBlockContext` and it provides `witness.Proof`, all schemes except S5 do `panic` when calling this method, only the `ArchiveTrie` supports it.  
An example is provided showing how to use.
=> integrates witness proof into public facade

go/state/gostate/go_schema5.go, go/state/gostate/go_schema5_test.go
This PR fixes an issue introduced by #950 related to the definition of very small node cache sizes.
Before #950, if a node cache size of less than a single node was specified, the MPT implementation would increase it to a minimum value of `2_000` nodes.
After #950, if a node cache size of less than a single node is specified, it got converted to a `capacity` definition of `0`, which lead to the utilization of the default cache size of `10_000_000` nodes. This lead to memory issue problems in Sonic tests.
With this fix, the old behavior was recovered.
=> Fix conversion of cache size to cache capacity

go/carmen/database_test.go, go/carmen/example_test.go, go/carmen/proof.go, go/common/witness/proof.go, go/database/mpt/proof.go, go/database/mpt/proof_test.go
This PR extends export capabilities of the WitnessProof. It was implemented on a request for easier integration to the RPC API.  It was detected that following features are missing for integration to the RPC
* `WitnessProof` contains MPT nodes for the whole proof in one structure, but the RPC returns two sets: MPT nodes for an account and MPT nodes for storage keys. 
* RPC API provides hash of the storage root from an account.
While all the data are encoded already in the `WitnessProof` and could be resolved at the RPC level, it was decided to help with integration by providing new extraction features by Carmen. 
In particular a method to extract sub-proof of a proof was made publicly available, and one method to extract storage nodes + storage root was added. 
As a result, account nodes, …
=> adds extraction features of witness proofs

go/state/state_db.go, go/state/state_db_mock.go, go/state/state_db_test.go
The whole RPC layer of Sonic currently use StateDB interface and migration to Carmen facade is not in sight. To avoid the need of passing the unwrapped State reference into the RPC, I want to add `CreateWitnessProof` method into the NonCommittableStateDB interface.
=> Make CreateWitnessProof accessible through StateDB interface

go/backend/utils/json_file_io.go, go/backend/utils/json_file_io_test.go
This PR adds two generic utility functions to simplify the reading and writing of small JSON files.
The need for those files was identified in #973 and #977.
=> Add generic utilities for Reading/Writing JSON files

go/database/mpt/dirty_directory_mark.go, go/database/mpt/dirty_directory_mark_test.go
This PR fixes a minor issue encountered while preparing test cases. A directory is not only identified as dirty if there is a file named `dirty` but also if there is a directory named `dirty`. This is not as it was originally intended.
By fixing this, it becomes simpler to create test cases where marking of a directory as dirty should fail.
=> Ignore directories when checking for dirty flags in directories

go/backend/stock/file/file.go, go/backend/stock/file/file_test.go, go/database/mpt/codes.go, go/database/mpt/codes_test.go
This PR add support or restoring the state of a pending checkpoint to file stocks and code stores.
This requirement was missed initially and discovered while working on the restoration of archives.
This PR contributes to #946.
=> Add ability to restore codes and stocks from pending commits

go/backend/archive/archive_test.go, go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_fuzzing_test.go, go/database/mpt/archive_trie_test.go, go/database/mpt/directory_lock.go, go/database/mpt/directory_lock_test.go, go/database/mpt/forest.go, go/database/mpt/io/archive.go, go/database/mpt/io/archive_test.go, go/database/mpt/io/interrupt_test.go, go/database/mpt/io/live.go, go/database/mpt/io/live_test.go, go/database/mpt/state_test.go, go/database/mpt/tool/block.go, go/database/mpt/tool/check.go, go/database/mpt/tool/info.go, go/database/mpt/tool/main.go, go/database/mpt/tool/reset.go, go/database/mpt/verification.go, go/database/mpt/visitor_test.go, go/state/gostate/configurations.go
This PR integrates checkpoint and recovery support into MPT archives. The main additions are:
- the periodic creation of checkpoints when adding blocks to an Archive
- the support for restoring arbitrary block heights preceding the last checkpoint
- the support for restoring corrupted archives using the MPT tool
This PR contributes to #946 
How to review this PR:
- the main additions are in the `database/mpt/archive_trie.go` file and the associated test file
- the feature of forcing the removal of a lock got added to `database/mpt/directory_lock.go` which is independent from the rest (if requested, it can be moved into its own PR)
- the command line support for restoring archives is added to `database/mpt/tool/reset.go` (could also be moved into its own PR if requested)
- all other files …
=> Add recovery support for Archive

go/database/mpt/archive_trie.go
The PR increases the default checkpoint interval to 1M blocks. 
The previous value of creating one checkpoint every 1000 blocks was to aggressive when syncing the archive. It was aiming for ~1 checkpoint every 10 minutes in live mode, but during syncing this would be more like 1 checkpoint every 2 seconds.
This change is a quick-fix to re-enable unit tests. As a follow-up a system-time dependent checkpoint triggering should be added (see #990).
=> Increase default checkpoint interval

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go
This PR updates the triggering mechanism for Archive checkpoints. Before this PR, checkpoints have been created periodically based on the block-height of the archive. This turned out to be too inflexible, since during archive sync times different intervals would be needed than while following the network traffic.
With this PR an new wall-clock time based triggering mechanism gets introduced. With this, the archive can be configured to create a checkpoint every X minutes -- in addition to the creation of checkpoints every Y blocks. This enables the flexible configuration of the checkpointing mechanism for production and test environment use cases.
This PR fixes #990
=> Add support for system-time based triggering of checkpoints

go/database/mpt/archive_trie_test.go
This PR disables a flaky test case causing the CI Race-Detection test to fail.
An initial investigation did not manage to reproduce this behavior on a local test system. More work is needed. In the meanwhile, disabling this test should re-instate the CI testing in the meanwhile.
Part of #994.
=> Disable flaky archive restore test

go/database/mpt/archive_trie.go, go/database/mpt/io/live.go
This PR improves the block-state exporting performance from an Archive. Before this fix, exporting block 10M from an Archive including 10M blocks took 5.5 minutes. With this change, this time got reduced to 2 minutes.
In the pprof profile the issue was clearly visible:
After this fix, this part of the overall processing is no longer visible in the profile.
In the old version of this code, the full code map was copied for each individual lookup, as the function
```
func (e exportableArchiveTrie) GetCodeForHash(hash common.Hash) []byte
```
accepts `e` by value. Thus, the fetched code map is dropped after each call.
Furthermore, there is no need to cache codes in the first place, as those are also cached by the Archive itself.
This is part of #997
=> Eliminate ineffective cache caching in Archive block state export

go/carmen/database_test.go, go/carmen/example_test.go, go/carmen/proof.go, go/carmen/proof_test.go, go/common/immutable/bytes.go, go/common/immutable/bytes_test.go, go/common/witness/proof.go, go/database/mpt/proof.go, go/database/mpt/proof_test.go
This PR introduces a new `immutable.Bytes`, which is a wrapped around bytes (strings) that cannot be modified from the outside, i.e. they are immutable. 
This new type is used in the Witness proof to represent original `[]string`, which could cause confusions as the string type was used to implement an immutable byte slice.
=> introduces immutable bytes and uses it in witness proof

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go
This PR adds a minor performance fix for opening Archives. Instead of gradually growing the root slice, it is allocated once while loading root node data from the disk.
This reduced loading time for the command
```
go run ./database/mpt/tool info /mnt/sonicdb/mainnet/carmen/archive
```
for an Archive with 88M blocks from 20 to 10 seconds.
The reduction can be seen in the CPU profile. Before:
After:
=> Pre-allocate slice for Archive roots

go/database/mpt/tool/benchmark.go, go/database/mpt/tool/block.go, go/database/mpt/tool/check.go, go/database/mpt/tool/export.go, go/database/mpt/tool/import.go, go/database/mpt/tool/info.go, go/database/mpt/tool/init_archive.go, go/database/mpt/tool/main.go, go/database/mpt/tool/reset.go, go/database/mpt/tool/stress.go, go/database/mpt/tool/verify.go
This PR adds general support for optional CPU coverage, tracing, and diagnoses services to all sub-commands of the MPT tool.
=> Expand performance diagnosing utilities to all commands

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go, go/database/mpt/forest.go, go/database/mpt/forest_test.go
this PR extends tracking of erroneous state of archive and forest. It seems it was forgotten to add this check at some newer code.
=> extends tracking of error states

go/database/mpt/io/live.go, go/database/mpt/io/live_test.go, go/database/mpt/io/log.go, go/database/mpt/io/log_test.go, go/state/gostate/archive_state.go
this PR introduces a method to export a livedb view from an archive, that is being currently online, accepting new blocks. This method accesses the archive independently on the main program by do not checking if the directory is locked, and allowing for accessing directly the directory.
=> Introduce method to export a LiveDB dump from a running Archive

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go, go/database/mpt/live_trie.go, go/database/mpt/live_trie_test.go, go/database/mpt/nodes.go, go/database/mpt/nodes_test.go, go/database/mpt/state.go, go/database/mpt/state_mocks.go
This PR introduces `VisitAccount`, `GetAccountInfo` and `CreateWitnessProof` method for tries. This method will be later needed for #947 to get nodes exclusively for accounts.
=> Introduce VisitAccount, GetAccountInfo, CreateWitnessProof methods for tries

scripts/db-heal-test.py
By using different working directories, multiple test script instances can be run in parallel for stress testing.
=> Add support for running multiple instances in parallel

go/database/mpt/archive_trie_test.go, go/database/mpt/diagnostics_test.go, go/database/mpt/forest_test.go, go/database/mpt/live_trie_test.go, go/database/mpt/node_flusher_test.go, go/database/mpt/root_hash_test.go
This PR adds optional diagnostics support to the MPT unit test. The main motivation is to identify memory leaks in the tests.
To enable diagnostic, export the `MPT_DIAGNOSTIC_PORT` environment variable before running tests, similar to this:
```
MPT_DIAGNOSTIC_PORT=6060 go test -v ./database/mpt
```
While the tests are running, the following command can be used to obtain a heap profile from the tests:
```
go tool pprof -http "localhost:8000" http://localhost:6060/debug/pprof/heap
```
In this profile, tests failing to free all their memory allocations (in particular failing to close all their MPT instances) can be identified.
=> Add diagnoses to MPT tests and start fixing memory leaks

go/database/mpt/forest_test.go
This PR closes unclosed forests in `forest_test.go` which leaked quite a lot a of memory.
=> Close leaking forests.

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go, go/database/mpt/live_trie.go, go/database/mpt/live_trie_test.go
This PR resolves problem with non-release resources when running tests of Live and Archive Trie.
=> check resource consumption archive+live tries tests

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go, go/database/mpt/config.go, go/database/mpt/config_test.go, go/database/mpt/io/live.go, go/database/mpt/io/parallel_visit.go, go/database/mpt/io/parallel_visit_test.go, go/database/mpt/live_trie.go, go/database/mpt/live_trie_test.go, go/database/mpt/nodes.go, go/database/mpt/state.go, go/database/mpt/state_test.go
This PR uses async reading of MPT to speed up export of liveDB.
Experiment was taken to export liveDB from a block height beyond 80M blocks, a cloud VM with local SSD.
Originally, the export took approx. **1 day**, after the change, it takes approx. **2 hours**.
=> uses async MPT reading to speed up live db export

go/database/mpt/config.go, go/database/mpt/config_test.go, go/database/mpt/forest.go, go/database/mpt/forest_test.go, go/database/mpt/verification.go, go/database/mpt/verification_test.go
This PR updates the code to use the public function of the config, GetEncoders, at every place where original getEncoder() was use.  This is a code clean-up.
=> makes use of GetEncoders, public function of config

go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go
This PR fixes a wrong calculation of capacity of the roots slice. It caused a high memory consumption as an unnecessarily big slice was pre-allocated.
=> fixes computation of roots slice capacity

go/database/mpt/io/parallel_visit.go, go/database/mpt/io/parallel_visit_test.go
This PR introduces two improvements to the parallel visit code:
- **throttling** of node pre-fetchers: workers stop prefetching nodes beyond a configurable threshold of prefetched nodes; however, since at the time workers are throttled not all needed nodes may have been fetched, the main thread is extended to contribute to the prefetching as needed, this puts a constant upper limit on the memory usage of the `visitAll` operation;
- **lockstep prefetching** of workers: workers will synchronize their activities to avoid prefetching large shares of far-future nodes and thereby exceeding the throttling limit for a long time. By synchronizing prefetch workers to load nodes in blocks, the focus of what is to be prefetched is forced to remain on the near future window.
For the latter, a …
=> Add throttling to node prefetchers

go/database/mpt/io/parallel_visit.go, go/database/mpt/io/parallel_visit_test.go
This PR resolves failures of tests, where the number of data produced by async workers in parallel trie visit is measured. 
The original code measured the total number of responses in the queue. It could easily exceed the expected limit, and the test failed. 
It seems that it was not originally intended by this test.  The test was supposed to measure only the volume of data produced by the workers, not to exceed memory limits by threads possibly rushing ahead in computation. 
During an execution, it can happen that all workers correctly stop producing data realising that too many responses were  produced. On the other hand, not to stall the execution, the main thread continues and still produces data, which piles up to the already existing number of responses. This is, correct behaviour …
=> sends only the number of responses coming from workers

go/backend/archive/ldb/archive.go, go/backend/depot/cache/cachedepot.go, go/backend/index/cache/cacheindex.go, go/backend/pagepool/pagepool.go, go/backend/pagepool/pagepool_test.go, go/backend/store/cache/cachedstore.go, go/state/gostate/go_state.go, go/state/gostate/go_state_test.go
This PR releases items stored in `LruCache` when components using this cache are `Closed`. This reduces memory in tests of state package.  Heap dumps below shows the memory allocated before and after this change. The dumps were captured right after all tests passed. 
Before:
After:
=> clear caches when closing resources to release memory

go/database/mpt/forest.go, go/database/mpt/forest_test.go, go/database/mpt/state_mocks.go, go/state/cppstate/cpp_state.go, go/state/gostate/archive_state.go, go/state/gostate/go_schema1.go, go/state/gostate/go_schema2.go, go/state/gostate/go_schema3.go, go/state/gostate/go_state.go, go/state/gostate/go_state_test.go, go/state/state.go, go/state/state_db.go, go/state/state_db_mock.go, go/state/state_db_test.go, go/state/state_mock.go, go/state/synced_state.go
There has been already a method to assess if a storage root of an account is empty or not.  This PR exposes this method to `State` and `StateDB`.
=> exposes method to assess empty storage of an account into State

go/state/state_db.go, go/state/state_db_mock.go, go/state/state_db_test.go
This PR fixes an issue in the API design of `HasEmptyStorage`.
While exported in `stateDb`, this method should not return an error. Errors are only tracked in stateDb, but not returned from each method.
=> fixes API issue in stateDB, HasEmptyStorage must not return error

go/carmen/carmen.go, go/carmen/query.go, go/carmen/query_test.go, go/carmen/transaction.go, go/carmen/transaction_test.go
This PR adds method `HasEmptyStorage` from `stateDB` to the public facade
=> introduces method HasEmptyStorge into carmen facade

go/backend/archive/archive.go, go/backend/archive/archive_mock.go, go/backend/archive/archive_test.go, go/backend/archive/ldb/archive.go, go/backend/archive/sqlite/archive.go, go/database/mpt/archive_trie.go, go/database/mpt/archive_trie_test.go, go/state/gostate/archive_state.go, go/state/gostate/archive_state_test.go
This PR adds `HasEmptyStorage` method into `Archive` backed by `ArchiveTrie`. For other schemes this method is not supported at the moment.
=> implements HasEmptyStorage in Archive

go/database/mpt/io/live.go
This PR changes the cache capacity for import to 200k and export to 2k.
This is necessary due to high memory consumption in Sonic integration tests. It lowers it by ~2 GB.
Measurements done on 20mil database:
Current main took `26:21`
This branch took `25:36`
=> Lower export LiveDB cache capacity

go/database/mpt/io/live.go
This PR updates import of liveDB. It reduces the number of loops when the hash is recomputed, and reduces the size of node cache. It reduces both 100 times. 
It was verified by importing ~90M block height that performance was not changed, while reducing the memory needs. 
New import took about 2,5h, the same time as it used to take before:
Running:
```
go run ./database/mpt/tool/ init-archive  /mnt/disks/ssd-array/live.dat /mnt/disks/ssd-array/init-archive
```
Before: 
```
2024/11/27 13:25:18 [t= 155:05] - imported 167000000 accounts, 62411.77 accounts/s
2024/11/27 13:25:38 [t= 155:25] - imported 168000000 accounts, 48905.98 accounts/s
2024/11/27 13:25:58 [t= 155:44] - imported 169000000 accounts, 51962.49 accounts/s
2024/11/27 13:26:13 [t= 156:00] - imported 170000000 accounts, 63809.84 …
```
=> decreases node cache size and number of import loops  

go/database/mpt/proof_test.go
This PR extends tests of WitnessProof methods `GetAccountElements` and `GetStorageElements`;
it tests that nodes returned from this methods are ordered according to navigation path in the MPT.
Furthermore, this PR extends code coverage, except two unimplemented methods, the code coverage is 100%.
=> tests path navigation order in witness proof
